### ISSUE TITLE
Issue with findng rosbag file

### ISSUE THREAD

**Issue by SunnyKatyara** [felixduvallet/grasp-synergy#9]
Hello dear concerned, since i am trying this code to calculate the synergy for my dexterous hand. When i launch the file, it is asking me for the ros bag file. I want to know the proper format for supplying the rosbag file to this launch file. What kind of msgs i should store in this ros bag file. If you have any example file, will appreciate if you can share.

Thank You

**Comment by felixduvallet** [comment]
I suggest you start with the sample data contained in this directory:
https://github.com/felixduvallet/grasp-synergy/tree/master/src/grasp_synergy/test
